config/routes.rb
LeezeMs::Application.routes.draw do
  resources :tours

end

app/models/category.rb
class Category < ActiveRecord::Base
 has_many :tour_categories
 has_many :tours, through: :tour_categories
end

app/models/tour.rb
class Tour < ActiveRecord::Base
  has_many :tour_categories
  has_many :categories, through: :tour_categories
  validates :title, :teaser, :description, :url, presence: true
  validates :url, format: %r|\Ahttp(s?)://www.google.com/maps|
end

app/models/tour_category.rb
class TourCategory < ActiveRecord::Base
  belongs_to :tour
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :set_tour, only: [:show, :edit, :update, :destroy]

  # GET /tours
  # GET /tours.json
  def index
    @tours = Tour.all
  end

  # GET /tours/1
  # GET /tours/1.json
  def show
  end

  # GET /tours/new
  def new
    @tour = Tour.new
  end

  # GET /tours/1/edit
  def edit
  end

  # POST /tours
  # POST /tours.json
  def create
    @tour = Tour.new(tour_params)

    respond_to do |format|
      if @tour.save
        format.html { redirect_to @tour, notice: 'Tour was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tour }
      else
        format.html { render action: 'new' }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tours/1
  # PATCH/PUT /tours/1.json
  def update
    respond_to do |format|
      if @tour.update(tour_params)
        format.html { redirect_to @tour, notice: 'Tour was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tours/1
  # DELETE /tours/1.json
  def destroy
    @tour.destroy
    respond_to do |format|
      format.html { redirect_to tours_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tour
      @tour = Tour.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tour_params
      params.require(:tour).permit(:title, :teaser, :description, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tours_helper.rb
module ToursHelper
  def iframe_url(tour)
  tour.url + "&output=embed"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LeezeMs</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tours/_form.html.erb
<%= form_for(@tour) do |f| %>
  <% if @tour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tour.errors.count, "error") %> prohibited this tour from being saved:</h2>

      <ul>
      <% @tour.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :teaser %><br>
    <%= f.text_field :teaser %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>

  <div>
   <%= f.label :category %><br>
   <%= f.collection_select :category_ids,
   Category.all, :id, :name, { selected: @tour.category_ids},
   {multiple: true } %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tours/edit.html.erb
<h1>Editing tour</h1>

<%= render 'form' %>

<%= link_to 'Show', @tour %> |
<%= link_to 'Back', tours_path %>

app/views/tours/index.html.erb
<h1>Listing tours</h1>



<ul>
 <% @tours.each do |tour| %>
  <li><%= link_to tour.title, tour %></li>
 <% end %>
</ul>

<br>

<%= link_to 'New Tour', new_tour_path %>

app/views/tours/new.html.erb
<h1>New tour</h1>

<%= render 'form' %>

<%= link_to 'Back', tours_path %>

app/views/tours/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @tour.title %>
</p>

<p>
  <strong>Teaser:</strong>
  <%= @tour.teaser %>
</p>

<p>
  <strong>Description:</strong>
  <%= @tour.description %>
</p>

<p>
 <iframe width=1200 height=600 frameborder=0 scrolling=no
 marginheight=0 marginwidth=0 src=<%= iframe_url(@tour)%>></
 iframe>
</p>

<%= link_to 'Edit', edit_tour_path(@tour) %> |
<%= link_to 'Back', tours_path %>